// Mocks generated by Mockito 5.4.6 from annotations
// in waterbus_sdk/test/features/auth/data/repositories/auth_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

import 'package:waterbus_sdk/types/externals/models/index.dart' as _i7;
import 'package:waterbus_sdk/types/result.dart' as _i2;

import 'package:waterbus_sdk/core/api/auth/datasources/auth_local_datasource.dart'
    as _i3;
import 'package:waterbus_sdk/core/api/auth/datasources/auth_remote_datasource.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i3.AuthLocalDataSource {
  @override
  String get accessToken => (super.noSuchMethod(
        Invocation.getter(#accessToken),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
      ) as String);

  @override
  String get refreshToken => (super.noSuchMethod(
        Invocation.getter(#refreshToken),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#refreshToken),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#refreshToken),
        ),
      ) as String);

  @override
  void saveTokens({
    required String? accessToken,
    required String? refreshToken,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteToken() => super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i5.AuthRemoteDataSource {
  @override
  _i6.Future<(String?, String?)> renewToken() => (super.noSuchMethod(
        Invocation.method(
          #renewToken,
          [],
        ),
        returnValue: _i6.Future<(String?, String?)>.value((null, null)),
        returnValueForMissingStub:
            _i6.Future<(String?, String?)>.value((null, null)),
      ) as _i6.Future<(String?, String?)>);

  @override
  _i6.Future<_i2.Result<_i7.User>> createToken(_i7.AuthPayload? authPayload) =>
      (super.noSuchMethod(
        Invocation.method(
          #createToken,
          [authPayload],
        ),
        returnValue:
            _i6.Future<_i2.Result<_i7.User>>.value(_FakeResult_0<_i7.User>(
          this,
          Invocation.method(
            #createToken,
            [authPayload],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Result<_i7.User>>.value(_FakeResult_0<_i7.User>(
          this,
          Invocation.method(
            #createToken,
            [authPayload],
          ),
        )),
      ) as _i6.Future<_i2.Result<_i7.User>>);

  @override
  _i6.Future<_i2.Result<bool>> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i6.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #deleteToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #deleteToken,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Result<bool>>);
}
