// Mocks generated by Mockito 5.4.4 from annotations
// in waterbus_sdk/test/features/meeting/domain/usecases/create_meeting_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i4;

// Package imports:
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:waterbus_sdk/types/error/failures.dart' as _i5;
import 'package:waterbus_sdk/types/index.dart' as _i6;

import 'package:waterbus_sdk/core/api/meetings/repositories/meeting_repository.dart'
    as _i3;
import 'package:waterbus_sdk/core/api/meetings/usecases/create_meeting.dart'
    as _i7;
import 'package:waterbus_sdk/core/api/meetings/usecases/get_info_meeting.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MeetingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingRepository extends _i1.Mock implements _i3.MeetingRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>> createMeeting(
          _i7.CreateMeetingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMeeting,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
            _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #createMeeting,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
                _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #createMeeting,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>> updateMeeting(
          _i7.CreateMeetingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMeeting,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
            _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #updateMeeting,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
                _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #updateMeeting,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>> joinMeetingWithPassword(
          _i7.CreateMeetingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinMeetingWithPassword,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
            _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #joinMeetingWithPassword,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
                _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #joinMeetingWithPassword,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>> joinMeetingWithoutPassword(
          _i7.CreateMeetingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinMeetingWithoutPassword,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
            _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #joinMeetingWithoutPassword,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
                _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #joinMeetingWithoutPassword,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>> getInfoMeeting(
          _i8.GetMeetingParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInfoMeeting,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
            _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #getInfoMeeting,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>.value(
                _FakeEither_0<_i5.Failure, _i6.Meeting>(
          this,
          Invocation.method(
            #getInfoMeeting,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Meeting>>);
}
